# Generated by Django 2.2.5 on 2019-12-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_duplicates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
