# Generated by Django 2.2.5 on 2019-12-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='list',
            name='email',
            field=models.EmailField(blank=True, default='email', max_length=70, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('id', 'email')},
        ),
    ]
